import { JarvisDatabase } from './database.mjs'; import { diagnostics } from './diagnostics.mjs'; import { LlamaCppProvider, OllamaProvider, OpenAICompatibleCloudProvider, ProviderError } from './providers.mjs'; import { canonicalRoot, readWorkspaceFile, registeredTools } from './tools.mjs';
import { AssistantEventHub } from './event-hub.mjs'; import { VoiceRuntime } from './voice-runtime.mjs';
export function createJarvisApp({ database, events = new AssistantEventHub() } = {}) {
  const db = database || new JarvisDatabase(); const providers = [new LlamaCppProvider(db.setting('provider.llamacpp', {})), new OllamaProvider(db.setting('provider.ollama', {})), new OpenAICompatibleCloudProvider(db.setting('provider.cloud', {}))]; const active = new Map(); const provider = (id) => providers.find((item) => item.id === id);
  const publish = (event) => events.publish(event); const voice = new VoiceRuntime({ database: db, publish });
  return {
    db, providers, events, voice, async initialize() { return this; },
    getProvider(id) { const selected = provider(id || db.setting('provider.active', 'llamacpp')); if (!selected) throw new ProviderError('Unknown provider.', 'unknown_provider'); return selected; },
    async health() { const info = await diagnostics(providers); return { status: 'ok', version: '0.1.0', loopbackOnly: true, providers: info.providers }; }, async diagnostics() { return diagnostics(providers); }, async models(providerId) { return this.getProvider(providerId).listModels(); },
    conversations: () => db.conversations(), conversation: (id) => { const item = db.conversation(id); return item && { ...item, messages: db.messages(id) }; }, createConversation(title) { return db.createConversation(title); },
    async *chat({ conversationId, content, providerId, model, allowCloud = false, signal, origin = 'desktop-text' }) {
      if (!content?.trim()) throw new ProviderError('Message is required.', 'validation'); const conversation = conversationId ? db.conversation(conversationId) : db.createConversation(content.trim().slice(0, 60)); if (!conversation) throw new ProviderError('Conversation not found.', 'not_found'); const selected = this.getProvider(providerId); const selectedModel = model || this.modelFor(selected.id) || (await selected.listModels())[0]; if (!selectedModel) throw new ProviderError(`Select a model for ${selected.label}.`, 'model_required'); if (!this.modelFor(selected.id)) db.setSetting(`provider.model.${selected.id}`, selectedModel); if (selected.id === 'cloud' && !allowCloud) throw new ProviderError('Cloud requests require explicit approval.', 'cloud_approval_required');
      if (active.has(conversation.id)) throw new ProviderError('This conversation already has an active turn.', 'turn_active'); const controller = new AbortController(); active.set(conversation.id, controller); if (signal) signal.addEventListener('abort', () => controller.abort(), { once: true }); db.addMessage(conversation.id, 'user', content.trim(), null, 'complete', origin); const history = db.messages(conversation.id).map((message) => ({ role: message.role, content: message.content })); let output = ''; yield { type: 'start', conversationId: conversation.id, provider: selected.id, model: selectedModel };
      publish({ type: 'session', state: 'turn-start', conversationId: conversation.id, origin });
      if (origin === 'voice') voice.setSession(conversation.id, 'thinking');
      try { for await (const token of selected.streamChat({ messages: history, model: selectedModel, signal: controller.signal })) { output += token; const event = { type: 'token', value: token, conversationId: conversation.id }; publish(event); yield event; } db.addMessage(conversation.id, 'assistant', output, selected.id, 'complete', origin); if (origin === 'voice') voice.setSession(conversation.id, 'speaking'); const done = { type: 'turn-complete', conversationId: conversation.id }; publish(done); yield done; } catch (error) { const status = controller.signal.aborted ? 'cancelled' : 'error'; if (output) db.addMessage(conversation.id, 'assistant', output, selected.id, status, origin); if (origin === 'voice') voice.setSession(conversation.id, status === 'cancelled' ? 'wake-listening' : 'error'); const event = { type: controller.signal.aborted ? 'cancelled' : 'error', code: error.code || status, conversationId: conversation.id, message: controller.signal.aborted ? 'Request cancelled.' : error.message }; publish(event); yield event; } finally { active.delete(conversation.id); }
    },
    cancel(conversationId) { const controller = active.get(conversationId); if (!controller) return false; controller.abort(); voice.interrupt(conversationId); return true; }, tools: registeredTools, roots: () => db.roots(), async addRoot(rootPath) { return db.addRoot(await canonicalRoot(rootPath)); }, removeRoot(id) { return db.removeRoot(id); }, async readFile(filePath) { return readWorkspaceFile(filePath, db.roots().map((root) => root.path)); }, modelFor(id) { return db.setting(`provider.model.${id}`, null); }, settings() { const activeProvider = db.setting('provider.active', 'llamacpp'); return { activeProvider, activeModel: this.modelFor(activeProvider), cloudConfigured: provider('cloud').enabled }; }, setActiveProvider(id) { this.getProvider(id); db.setSetting('provider.active', id); }, setModel(providerId, model) { const selected = this.getProvider(providerId); if (!model?.trim()) throw new ProviderError('Model is required.', 'model_required'); db.setSetting(`provider.model.${selected.id}`, model.trim()); }
  };
}
